### PR TITLE
Update frFR.lua

### PR DESCRIPTION
**Pull request by Machou**

### CODE REVIEW

**Comment by Machou** [comment]
Problem with:

L.WINDOW_BUTTON_SETTINGS =				"Open the settings."

On the button minimap, no space, so i have added a space, but on the setting, there a double space.

Like :

Capture d’écran 2024-10-20 221439

**Comment by Sluimerstand** [comment]
We can solve that by changing `app.IconRMB .. " :" .. L.WINDOW_BUTTON_SETTINGS` in `L.SETTINGS_TOOLTIP`
to `app.IconRMB .. " : " .. L.WINDOW_BUTTON_SETTINGS` instead of directly adjusting `L.WINDOW_BUTTON_SETTINGS`

Other question though, why remove all the periods to end the sentences, and in this case even the colon?
image

**Comment by Machou** [comment]
> We can solve that by changing `app.IconRMB .. " :" .. L.WINDOW_BUTTON_SETTINGS` in `L.SETTINGS_TOOLTIP` to `app.IconRMB .. " : " .. L.WINDOW_BUTTON_SETTINGS` instead of directly adjusting `L.WINDOW_BUTTON_SETTINGS`
> 
> Other question though, why remove all the periods to end the sentences, and in this case even the colon? image

In French, when writing a definition in list or dictionary form, it's not necessary to put a period at the end if the definition is short and presents itself as a simple correspondence.

It's more beautiful without "." :D

**Comment by Sluimerstand** [comment]
That specific example and a lot of the other instances aren't lists or displayed together though. This specific example are chat messages sent to the user and should be treated as full sentences, for example. 🤔

**Comment by Machou** [comment]
> That specific example and a lot of the other instances aren't lists or displayed together though. This specific example are chat messages sent to the user and should be treated as full sentences, for example. 🤔

It's your addon, you make the final decision, of course. But in French you write without a period at the end, if it's not a sentence. It's not a big deal, aesthetically speaking.

**Comment by Sluimerstand** [comment]
I'll review which strings are full sentences and which are loose definitions/lists, and update accordingly. ❤️

**Pull request merged**
